pub(super) fn modifier_flag_value(modifier: &str) -> Result<u64, String> {
    match modifier {
        "Ctrl" => Ok(0x0004_0000),
        "Shift" => Ok(0x0002_0000),
        "Alt" => Ok(0x0008_0000),
        "Meta" => Ok(0x0010_0000),
        other => Err(format!("Unsupported macOS modifier: {}", other)),
    }
}

pub(super) fn key_to_macos_key_code(value: &str) -> Result<u16, String> {
    let upper = value.to_uppercase();
    let key_code = match upper.as_str() {
        "A" => 0,
        "S" => 1,
        "D" => 2,
        "F" => 3,
        "H" => 4,
        "G" => 5,
        "Z" => 6,
        "X" => 7,
        "C" => 8,
        "V" => 9,
        "B" => 11,
        "Q" => 12,
        "W" => 13,
        "E" => 14,
        "R" => 15,
        "Y" => 16,
        "T" => 17,
        "1" => 18,
        "2" => 19,
        "3" => 20,
        "4" => 21,
        "6" => 22,
        "5" => 23,
        "EQUAL" | "PLUS" => 24,
        "9" => 25,
        "7" => 26,
        "MINUS" => 27,
        "8" => 28,
        "0" => 29,
        "BRACKETRIGHT" => 30,
        "O" => 31,
        "U" => 32,
        "BRACKETLEFT" => 33,
        "I" => 34,
        "P" => 35,
        "ENTER" => 36,
        "L" => 37,
        "J" => 38,
        "QUOTE" => 39,
        "K" => 40,
        "SEMICOLON" => 41,
        "BACKSLASH" => 42,
        "COMMA" => 43,
        "SLASH" => 44,
        "N" => 45,
        "M" => 46,
        "PERIOD" => 47,
        "TAB" => 48,
        "SPACE" => 49,
        "BACKQUOTE" => 50,
        "BACKSPACE" => 51,
        "ESCAPE" => 53,
        "COMMAND" | "META" => 55,
        "SHIFT" => 56,
        "ALT" => 58,
        "CONTROL" | "CTRL" => 59,
        "F17" => 64,
        "NUMPADDECIMAL" => 65,
        "NUMPADMULTIPLY" => 67,
        "NUMPADADD" => 69,
        "NUMPADCLEAR" => 71,
        "NUMPADDIVIDE" => 75,
        "NUMPADENTER" => 76,
        "NUMPADSUBTRACT" => 78,
        "F18" => 79,
        "F19" => 80,
        "NUMPADEQUAL" => 81,
        "NUMPAD0" => 82,
        "NUMPAD1" => 83,
        "NUMPAD2" => 84,
        "NUMPAD3" => 85,
        "NUMPAD4" => 86,
        "NUMPAD5" => 87,
        "NUMPAD6" => 88,
        "NUMPAD7" => 89,
        "F20" => 90,
        "NUMPAD8" => 91,
        "NUMPAD9" => 92,
        "F5" => 96,
        "F6" => 97,
        "F7" => 98,
        "F3" => 99,
        "F8" => 100,
        "F9" => 101,
        "F11" => 103,
        "F13" => 105,
        "F16" => 106,
        "F14" => 107,
        "F10" => 109,
        "F12" => 111,
        "F15" => 113,
        "HOME" => 115,
        "PAGEUP" => 116,
        "DELETE" => 117,
        "F4" => 118,
        "END" => 119,
        "F2" => 120,
        "PAGEDOWN" => 121,
        "F1" => 122,
        "ARROWLEFT" | "LEFT" => 123,
        "ARROWRIGHT" | "RIGHT" => 124,
        "ARROWDOWN" | "DOWN" => 125,
        "ARROWUP" | "UP" => 126,
        _ => return Err(format!("Unsupported macOS key: {}", value)),
    };

    Ok(key_code)
}

pub(super) fn mouse_to_macos_button(value: &str) -> Result<u32, String> {
    let upper = value.to_uppercase();
    let button = match upper.as_str() {
        "MOUSELEFT" => 0,
        "MOUSERIGHT" => 1,
        "MOUSEMIDDLE" => 2,
        "MOUSE4" => 3,
        "MOUSE5" => 4,
        _ => return Err(format!("Unsupported macOS mouse button: {}", value)),
    };

    Ok(button)
}
